/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;
import DoiTuong.NguoiDung;
import DAO.QuanLyNguoiDung;
import java.awt.Color;
import java.util.Arrays;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class Login extends javax.swing.JFrame {
    private final QuanLyNguoiDung qlnd;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.btnDangNhap.setBackground(Color.white);
        this.qlnd = new QuanLyNguoiDung();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKhungLogin = new javax.swing.JPanel();
        lblTenBenhVien = new javax.swing.JLabel();
        lblTenDangNhap = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();
        lblNen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        setBackground(new java.awt.Color(102, 204, 204));
        setPreferredSize(new java.awt.Dimension(1200, 562));
        getContentPane().setLayout(null);

        pnlKhungLogin.setBackground(new java.awt.Color(102, 204, 204));
        pnlKhungLogin.setMaximumSize(null);
        pnlKhungLogin.setPreferredSize(new java.awt.Dimension(620, 340));

        lblTenBenhVien.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblTenBenhVien.setForeground(new java.awt.Color(255, 255, 255));
        lblTenBenhVien.setText("Bệnh viện Agile");

        lblTenDangNhap.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTenDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        lblTenDangNhap.setText("Tên đăng nhập");

        lblMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblMatKhau.setText("Mật khẩu");

        txtTenDangNhap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTenDangNhap.setForeground(new java.awt.Color(102, 204, 204));
        txtTenDangNhap.setPreferredSize(new java.awt.Dimension(387, 38));

        txtMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMatKhau.setForeground(new java.awt.Color(102, 204, 204));
        txtMatKhau.setPreferredSize(new java.awt.Dimension(387, 38));

        btnDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(102, 204, 204));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setPreferredSize(new java.awt.Dimension(170, 44));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKhungLoginLayout = new javax.swing.GroupLayout(pnlKhungLogin);
        pnlKhungLogin.setLayout(pnlKhungLoginLayout);
        pnlKhungLoginLayout.setHorizontalGroup(
            pnlKhungLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungLoginLayout.createSequentialGroup()
                .addGroup(pnlKhungLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKhungLoginLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(lblTenBenhVien))
                    .addGroup(pnlKhungLoginLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKhungLoginLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(pnlKhungLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenDangNhap)
                            .addComponent(lblMatKhau))
                        .addGap(28, 28, 28)
                        .addGroup(pnlKhungLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        pnlKhungLoginLayout.setVerticalGroup(
            pnlKhungLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungLoginLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTenBenhVien)
                .addGap(40, 40, 40)
                .addGroup(pnlKhungLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenDangNhap)
                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlKhungLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhau)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        getContentPane().add(pnlKhungLogin);
        pnlKhungLogin.setBounds(68, 128, 620, 340);
        pnlKhungLogin.getAccessibleContext().setAccessibleName("");

        lblNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TaiNguyen/Backgroud_Login.png"))); // NOI18N
        getContentPane().add(lblNen);
        lblNen.setBounds(0, 0, 1200, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        String tdn = this.txtTenDangNhap.getText();
        char[] mk = this.txtMatKhau.getPassword();
        if(tdn.length()==0){
            JOptionPane.showMessageDialog(this, "Tên đăng nhập không được để trống!");
            this.txtTenDangNhap.setBackground(Color.yellow);
            this.txtTenDangNhap.requestFocus();
            return;
        }else if(tdn.length()>10 || tdn.length()<6){
            JOptionPane.showMessageDialog(this, "Tên đăng nhập không được quá 10 kí tự và lớn hơn 6 kí tự!");
            this.txtTenDangNhap.setBackground(Color.yellow);
            this.txtTenDangNhap.requestFocus();
            return;
        }else{
            this.txtTenDangNhap.setBackground(Color.white);
        }
        
        if(mk.length==0){
            JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống!");
            this.txtMatKhau.setBackground(Color.yellow);
            this.txtMatKhau.requestFocus();
            return;
        }else{
            this.txtMatKhau.setBackground(Color.white);
        }
        String chucVu="";
        String pw = "123456789";
        if(tdn.equalsIgnoreCase("QuanTri")&&Arrays.equals(mk, pw.toCharArray())){
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
            QuanLyNguoiDung_Frame qtnd = new QuanLyNguoiDung_Frame();
            qtnd.setVisible(true);
            this.dispose();
            return;
        }
        try {
            NguoiDung n = this.qlnd.dangNhap(tdn);
            if(n==null){
                JOptionPane.showMessageDialog(this, "Tên đăng nhập không tồn tại!");
                this.txtTenDangNhap.setBackground(Color.yellow);
                this.txtTenDangNhap.requestFocus();
                return;
            }else{
                this.txtTenDangNhap.setBackground(Color.white);
            }
            char[] pass = n.getPass().toCharArray();
            if(Arrays.equals(mk, pass)==false){
                JOptionPane.showMessageDialog(this, "Mật khẩu không chính xác!");
                this.txtMatKhau.setBackground(Color.yellow);
                this.txtMatKhau.requestFocus();
                return;
            }else{
                this.txtMatKhau.setBackground(Color.white);
            }
            chucVu = n.getChucVu();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối máy chủ !");
            return;
        }
        JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
        if(chucVu.equalsIgnoreCase("BS")){
            TrangChu tc = new TrangChu("BS", "123",tdn);
            tc.setVisible(true);
            this.dispose();
        }else if(chucVu.equalsIgnoreCase("YT")){
            TrangChu tc = new TrangChu("YT", "123",tdn);
            tc.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblNen;
    private javax.swing.JLabel lblTenBenhVien;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JPanel pnlKhungLogin;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
