/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TrangChu extends javax.swing.JFrame {
    private final String userName;
    private final String passWord;
    private final String ND;
    /**
     * Creates new form TrangChu
     */
    public TrangChu(String userName, String passWord, String ND) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.userName = userName;
        this.passWord = passWord;
        this.ND = ND;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblTieuDe = new javax.swing.JLabel();
        pnlBNNoiTru = new javax.swing.JPanel();
        lblChuTren = new javax.swing.JLabel();
        lblChuDuoi = new javax.swing.JLabel();
        lblAnhBNNoiTru = new javax.swing.JLabel();
        pnlBNNgoaiTru = new javax.swing.JPanel();
        lblChuTren1 = new javax.swing.JLabel();
        lblChuDuoi1 = new javax.swing.JLabel();
        lblBNNgoaiTru = new javax.swing.JLabel();
        pnlThanhToan = new javax.swing.JPanel();
        lblThanhToan = new javax.swing.JLabel();
        lblChuTren2 = new javax.swing.JLabel();
        lblChuDuoi2 = new javax.swing.JLabel();
        pnlDangXuat = new javax.swing.JPanel();
        lblDangXuat = new javax.swing.JLabel();
        lblChuTren3 = new javax.swing.JLabel();
        lblNen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(10, 10));
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1125, 692));
        setPreferredSize(new java.awt.Dimension(1125, 692));
        getContentPane().setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TaiNguyen/logoTrangChu.PNG"))); // NOI18N
        getContentPane().add(lblLogo);
        lblLogo.setBounds(60, 50, 178, 150);

        lblTieuDe.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(102, 204, 204));
        lblTieuDe.setText("BỆNH VIỆN AGILE");
        getContentPane().add(lblTieuDe);
        lblTieuDe.setBounds(370, 80, 560, 100);

        pnlBNNoiTru.setBackground(new java.awt.Color(255, 255, 255));
        pnlBNNoiTru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        pnlBNNoiTru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBNNoiTruMouseClicked(evt);
            }
        });
        pnlBNNoiTru.setLayout(null);

        lblChuTren.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblChuTren.setForeground(new java.awt.Color(102, 204, 204));
        lblChuTren.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChuTren.setText("Bệnh nhân");
        lblChuTren.setMaximumSize(new java.awt.Dimension(150, 37));
        pnlBNNoiTru.add(lblChuTren);
        lblChuTren.setBounds(10, 160, 160, 40);

        lblChuDuoi.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblChuDuoi.setForeground(new java.awt.Color(102, 204, 204));
        lblChuDuoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChuDuoi.setText("nội trú");
        lblChuDuoi.setMaximumSize(new java.awt.Dimension(150, 37));
        pnlBNNoiTru.add(lblChuDuoi);
        lblChuDuoi.setBounds(10, 200, 160, 40);

        lblAnhBNNoiTru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TaiNguyen/iconNoiTru(TrangChu).PNG"))); // NOI18N
        pnlBNNoiTru.add(lblAnhBNNoiTru);
        lblAnhBNNoiTru.setBounds(10, 10, 160, 150);

        getContentPane().add(pnlBNNoiTru);
        pnlBNNoiTru.setBounds(100, 290, 180, 240);

        pnlBNNgoaiTru.setBackground(new java.awt.Color(255, 255, 255));
        pnlBNNgoaiTru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        pnlBNNgoaiTru.setMinimumSize(new java.awt.Dimension(160, 230));
        pnlBNNgoaiTru.setPreferredSize(new java.awt.Dimension(160, 230));
        pnlBNNgoaiTru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBNNgoaiTruMouseClicked(evt);
            }
        });
        pnlBNNgoaiTru.setLayout(null);

        lblChuTren1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblChuTren1.setForeground(new java.awt.Color(102, 204, 204));
        lblChuTren1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChuTren1.setText("Bệnh nhân");
        lblChuTren1.setMaximumSize(new java.awt.Dimension(150, 37));
        pnlBNNgoaiTru.add(lblChuTren1);
        lblChuTren1.setBounds(10, 160, 160, 40);

        lblChuDuoi1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblChuDuoi1.setForeground(new java.awt.Color(102, 204, 204));
        lblChuDuoi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChuDuoi1.setText("ngoại trú");
        lblChuDuoi1.setMaximumSize(new java.awt.Dimension(150, 37));
        pnlBNNgoaiTru.add(lblChuDuoi1);
        lblChuDuoi1.setBounds(10, 200, 160, 40);

        lblBNNgoaiTru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TaiNguyen/iconNgoaiTru(TrangChu).PNG"))); // NOI18N
        pnlBNNgoaiTru.add(lblBNNgoaiTru);
        lblBNNgoaiTru.setBounds(10, 10, 160, 150);

        getContentPane().add(pnlBNNgoaiTru);
        pnlBNNgoaiTru.setBounds(330, 290, 180, 240);

        pnlThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        pnlThanhToan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        pnlThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThanhToanMouseClicked(evt);
            }
        });
        pnlThanhToan.setLayout(null);

        lblThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TaiNguyen/iconThanhToan(TrangChu).PNG"))); // NOI18N
        lblThanhToan.setText("jLabel1");
        pnlThanhToan.add(lblThanhToan);
        lblThanhToan.setBounds(10, 10, 160, 155);

        lblChuTren2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblChuTren2.setForeground(new java.awt.Color(102, 204, 204));
        lblChuTren2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChuTren2.setText("Thanh toán");
        lblChuTren2.setMaximumSize(new java.awt.Dimension(150, 37));
        pnlThanhToan.add(lblChuTren2);
        lblChuTren2.setBounds(10, 160, 160, 40);

        lblChuDuoi2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblChuDuoi2.setForeground(new java.awt.Color(102, 204, 204));
        lblChuDuoi2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChuDuoi2.setText("viện phí");
        lblChuDuoi2.setMaximumSize(new java.awt.Dimension(150, 37));
        pnlThanhToan.add(lblChuDuoi2);
        lblChuDuoi2.setBounds(10, 200, 160, 40);

        getContentPane().add(pnlThanhToan);
        pnlThanhToan.setBounds(570, 290, 180, 240);

        pnlDangXuat.setBackground(new java.awt.Color(255, 255, 255));
        pnlDangXuat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        pnlDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDangXuatMouseClicked(evt);
            }
        });
        pnlDangXuat.setLayout(null);

        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TaiNguyen/iconExit(TrangChu).png"))); // NOI18N
        pnlDangXuat.add(lblDangXuat);
        lblDangXuat.setBounds(10, 10, 160, 155);

        lblChuTren3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblChuTren3.setForeground(new java.awt.Color(102, 204, 204));
        lblChuTren3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChuTren3.setText("Đăng xuất");
        lblChuTren3.setMaximumSize(new java.awt.Dimension(150, 37));
        pnlDangXuat.add(lblChuTren3);
        lblChuTren3.setBounds(10, 180, 160, 50);

        getContentPane().add(pnlDangXuat);
        pnlDangXuat.setBounds(810, 290, 180, 240);

        lblNen.setBackground(new java.awt.Color(255, 255, 255));
        lblNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TaiNguyen/background.jpg"))); // NOI18N
        lblNen.setMinimumSize(new java.awt.Dimension(1125, 692));
        getContentPane().add(lblNen);
        lblNen.setBounds(0, 0, 1125, 692);

        getAccessibleContext().setAccessibleName("Trang chủ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlBNNoiTruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBNNoiTruMouseClicked
        BenhNhanNoiTru nt = new BenhNhanNoiTru(userName, passWord, ND);
        nt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlBNNoiTruMouseClicked

    private void pnlBNNgoaiTruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBNNgoaiTruMouseClicked
        BenhNhanNgoaiiTru nt = new BenhNhanNgoaiiTru(userName, passWord, ND);
        nt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlBNNgoaiTruMouseClicked

    private void pnlThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThanhToanMouseClicked
        ThanhToanVienPhi tt = new ThanhToanVienPhi(userName, passWord, ND);
        tt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlThanhToanMouseClicked

    private void pnlDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDangXuatMouseClicked
        int ok = JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất?","Đăng xuất",JOptionPane.YES_NO_OPTION);
        if(ok==JOptionPane.YES_OPTION){
            Login lg = new Login();
            lg.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_pnlDangXuatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAnhBNNoiTru;
    private javax.swing.JLabel lblBNNgoaiTru;
    private javax.swing.JLabel lblChuDuoi;
    private javax.swing.JLabel lblChuDuoi1;
    private javax.swing.JLabel lblChuDuoi2;
    private javax.swing.JLabel lblChuTren;
    private javax.swing.JLabel lblChuTren1;
    private javax.swing.JLabel lblChuTren2;
    private javax.swing.JLabel lblChuTren3;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNen;
    private javax.swing.JLabel lblThanhToan;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlBNNgoaiTru;
    private javax.swing.JPanel pnlBNNoiTru;
    private javax.swing.JPanel pnlDangXuat;
    private javax.swing.JPanel pnlThanhToan;
    // End of variables declaration//GEN-END:variables
}
